# Generated by Django 5.0.2 on 2024-02-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='no_of_rating',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='total_rating',
        ),
    ]
