# Generated by Django 5.0.2 on 2024-03-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_no_of_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='address',
            new_name='RollNo',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='zipcode',
            new_name='YearsOld',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='city',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='state',
            new_name='year',
        ),
    ]
