# Generated by Django 5.0.2 on 2024-03-01 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_address_listing_rollno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='YearsOld',
            new_name='yearsold',
        ),
    ]
