# Generated by Django 5.0.2 on 2024-03-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_yearsold_listing_yearsold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='yearsold',
            new_name='yearsOld',
        ),
    ]
